### ISSUE TITLE
Webhooks CallBack URL Error

### ISSUE THREAD

**Issue by Shrunoti** [hartleybrody/fb-messenger-bot#12]
I got this error message when setup the webhook
![screenshot from 2016-12-29 13 04 02](https://cloud.githubusercontent.com/assets/18402893/21538944/f96fcd1e-cdc7-11e6-83ee-a866190d9080.png)

**Comment by AurDan** [comment]
Hello, it probably comes from here https://github.com/hartleybrody/fb-messenger-bot/blob/master/app.py#L17 , so due to a wrong verify token. Did you set it on Heroku settings ?

**Comment by hartleybrody** [comment]
@AurDan Thanks for chiming in to help! I think you're exactly right. I've just updated the project's README to address this issue since it seems to get reported every other week.
