### ISSUE TITLE
Unable to setup local

### ISSUE THREAD

**Issue by dipakkr** [hartleybrody/fb-messenger-bot#13]
![py_local](https://cloud.githubusercontent.com/assets/17788569/21777672/ca722f14-d6c5-11e6-8dfc-fc5df6587a00.PNG)

I am unable to run app locally. @hartleybrody

**Comment by hartleybrody** [comment]
Looking through that stacktrace you posted, there isn't a line that comes from any of the code in this project. A quick google search seems to indicate that this is a windows compatibility issue.

[Please at least attempt to solve your own issue before opening an issue here.](http://lmgtfy.com/?q=no+module+named+fcntl)
