### ISSUE TITLE
sometimes I get OAuthException

### ISSUE THREAD

**Issue by AndreiD** [hartleybrody/fb-messenger-bot#7]
everything works good, bot responds...all ok
but sometimes I get

{"error":{"message":"(#100) No matching user found","type":"OAuthException","code":100,"fbtrace_id":"H88xneLGeNw"}}

I wonder why ?

**Comment by hartleybrody** [comment]
Not 100% sure without knowing more about what's happening or seeing a stack trace. I imagine you're getting this error when you're attempting to send a message back to someone? 

Maybe you're not storing the incoming message's user ID correctly, or maybe you don't have API access to send that user a message. Remember that the bot can only message with admins of your page until it has been "approved" by the facebook team.

Either way, I'm closing this as it's not an issue on my codebase.
