### ISSUE TITLE
Does fb_messenger_bot support for Chinese talk？

### ISSUE THREAD

**Issue by MrZhw** [hartleybrody/fb-messenger-bot#9]
I wanna know whether i can use it to communicate in Chinese.

**Comment by hartleybrody** [comment]
I haven't tested it with Chinese characters, and to be honest, don't have much experience building software to support those characters. I obviously make no guarantees about the fitness of this code for any specific purposes, as is common with freely available open source software.

Having disclaimed all of that, all that my code does is play ping-pong with Facebook's chat API. As far as I know, all of the libraries I'm using support UTF-8 characters so I see no reason why this wouldn't work with Chinese characters, emojis or any other types of characters.

It'd be pretty trivial to update the example code to echo back the message it received and see if it can properly receive and send the types of characters you'd like to support. Hope that helps!
